const mongoose = require("mongoose");

const scheduleSchema = new mongoose.Schema({
  cropType: String,
  soilType: String,
  location: String,
  irrigationNeeded: String,
  scheduledDate: Date,
  phoneNumber: String,
  autoGenerated: Boolean,
  userId: {
  type: mongoose.Schema.Types.ObjectId,
  ref: 'User',
  required: true
}
});

module.exports = mongoose.model("Schedule", scheduleSchema);
